export const MOCK_NEWS = [
  // Tier 5 - Critical (always visible)
  { id: '1', title: 'Major conflict escalation in Eastern Europe', lat: 50.45, lng: 30.52, category: 'war_conflict', importance: 5, magnitude: 3, source: 'Reuters', publishedAt: new Date().toISOString(), url: 'https://www.reuters.com', description: 'Significant escalation reported near border regions with international response mounting.' },
  { id: '2', title: 'Massive earthquake strikes Southeast Asia', lat: 13.75, lng: 100.52, category: 'environment_climate', importance: 5, magnitude: 3, source: 'BBC News', publishedAt: new Date().toISOString(), url: 'https://www.bbc.com', description: 'A 7.8 magnitude earthquake has struck the region causing widespread damage.' },
  { id: '3', title: 'Global markets in freefall amid banking crisis', lat: 40.71, lng: -74.01, category: 'finance_markets', importance: 5, magnitude: 3, source: 'Bloomberg', publishedAt: new Date().toISOString(), url: 'https://www.bloomberg.com', description: 'Wall Street experiences sharpest decline in a decade as banking sector faces liquidity concerns.' },
  { id: '4', title: 'Emergency UN Security Council session called', lat: 40.75, lng: -73.97, category: 'world_international', importance: 5, magnitude: 2, source: 'Al Jazeera', publishedAt: new Date().toISOString(), url: 'https://www.aljazeera.com', description: 'All permanent members to attend emergency session on escalating international crisis.' },
  { id: '5', title: 'Unprecedented flooding devastates South America', lat: -23.55, lng: -46.63, category: 'environment_climate', importance: 5, magnitude: 3, source: 'Associated Press', publishedAt: new Date().toISOString(), url: 'https://apnews.com', description: 'Record rainfall causes catastrophic flooding across multiple Brazilian states.' },

  // Tier 4 - High
  { id: '6', title: 'NATO holds emergency defense summit', lat: 50.85, lng: 4.35, category: 'world_international', importance: 4, magnitude: 2, source: 'CNN', publishedAt: new Date().toISOString(), url: 'https://www.cnn.com', description: 'Alliance members discuss collective defense posture amid rising tensions.' },
  { id: '7', title: 'Central bank announces surprise rate hike', lat: 51.51, lng: -0.13, category: 'finance_markets', importance: 4, magnitude: 2, source: 'Financial Times', publishedAt: new Date().toISOString(), url: 'https://www.ft.com', description: 'Bank of England raises rates by 50 basis points in unexpected move.' },
  { id: '8', title: 'Tropical cyclone approaches Australian coast', lat: -27.47, lng: 153.03, category: 'environment_climate', importance: 4, magnitude: 2, source: 'ABC News (AU)', publishedAt: new Date().toISOString(), url: 'https://www.abc.net.au/news', description: 'Category 4 cyclone expected to make landfall within 48 hours.' },
  { id: '9', title: 'Historic peace accord signed in Middle East', lat: 24.71, lng: 46.68, category: 'world_international', importance: 4, magnitude: 2, source: 'Al Jazeera', publishedAt: new Date().toISOString(), url: 'https://www.aljazeera.com', description: 'Two nations sign landmark agreement ending decades of diplomatic freeze.' },
  { id: '10', title: 'Major humanitarian crisis in East Africa', lat: 2.05, lng: 45.32, category: 'human_interest', importance: 4, magnitude: 2, source: 'Reuters', publishedAt: new Date().toISOString(), url: 'https://www.reuters.com', description: 'UN warns of imminent famine affecting millions across the Horn of Africa.' },

  // Tier 3 - Medium
  { id: '11', title: 'EU proposes sweeping AI regulation framework', lat: 50.85, lng: 4.35, category: 'science_technology', importance: 3, magnitude: 1, source: 'The Guardian', publishedAt: new Date().toISOString(), url: 'https://www.theguardian.com', description: 'New regulatory proposal could reshape the global AI industry.' },
  { id: '12', title: 'India launches ambitious space mission', lat: 13.07, lng: 80.24, category: 'space_astronomy', importance: 3, magnitude: 1, source: 'Times of India', publishedAt: new Date().toISOString(), url: 'https://timesofindia.indiatimes.com', description: 'ISRO successfully launches next-generation lunar probe.' },
  { id: '13', title: 'Japan and South Korea reach trade agreement', lat: 35.68, lng: 139.69, category: 'business_economy', importance: 3, magnitude: 1, source: 'Bloomberg', publishedAt: new Date().toISOString(), url: 'https://www.bloomberg.com', description: 'Historic trade deal expected to boost bilateral commerce by 30%.' },
  { id: '14', title: 'Breakthrough cancer treatment approved in Europe', lat: 48.86, lng: 2.35, category: 'health_medicine', importance: 3, magnitude: 1, source: 'BBC News', publishedAt: new Date().toISOString(), url: 'https://www.bbc.com', description: 'Revolutionary immunotherapy shows 90% remission rate in clinical trials.' },
  { id: '15', title: 'G20 climate summit reaches new emissions deal', lat: -15.79, lng: -47.88, category: 'environment_climate', importance: 3, magnitude: 1, source: 'Reuters', publishedAt: new Date().toISOString(), url: 'https://www.reuters.com', description: 'Nations commit to accelerated carbon reduction targets.' },
  { id: '16', title: 'Refugee crisis intensifies along Mediterranean', lat: 36.72, lng: 3.09, category: 'human_interest', importance: 3, magnitude: 1, source: 'Al Jazeera', publishedAt: new Date().toISOString(), url: 'https://www.aljazeera.com', description: 'Record number of crossings reported this quarter amid ongoing conflicts.' },
  { id: '17', title: 'Tech giants face antitrust action in Asia', lat: 37.57, lng: 126.98, category: 'business_economy', importance: 3, magnitude: 1, source: 'CNBC', publishedAt: new Date().toISOString(), url: 'https://www.cnbc.com', description: 'South Korean regulators launch major investigation into market dominance.' },

  // Tier 2 - Standard
  { id: '18', title: 'New renewable energy record set in Germany', lat: 52.52, lng: 13.41, category: 'environment_climate', importance: 2, magnitude: 1, source: 'The Guardian', publishedAt: new Date().toISOString(), url: 'https://www.theguardian.com', description: 'Wind and solar generate 80% of national grid for the first time.' },
  { id: '19', title: 'Mexico announces infrastructure investment plan', lat: 19.43, lng: -99.13, category: 'business_economy', importance: 2, magnitude: 1, source: 'Bloomberg', publishedAt: new Date().toISOString(), url: 'https://www.bloomberg.com', description: '$50 billion infrastructure program targets transportation and digital connectivity.' },
  { id: '20', title: 'Aid organizations expand operations in Sudan', lat: 15.59, lng: 32.53, category: 'human_interest', importance: 2, magnitude: 1, source: 'Reuters', publishedAt: new Date().toISOString(), url: 'https://www.reuters.com', description: 'International NGOs increase presence as humanitarian needs grow.' },
  { id: '21', title: 'Russia unveils new Arctic development strategy', lat: 55.76, lng: 37.62, category: 'world_international', importance: 2, magnitude: 1, source: 'BBC News', publishedAt: new Date().toISOString(), url: 'https://www.bbc.com', description: 'Comprehensive plan for Northern Sea Route development announced.' },
  { id: '22', title: 'Canada passes digital privacy legislation', lat: 45.42, lng: -75.70, category: 'politics_government', importance: 2, magnitude: 1, source: 'CNN', publishedAt: new Date().toISOString(), url: 'https://www.cnn.com', description: 'New law establishes strict data protection requirements for tech companies.' },

  // Tier 1 - Local
  { id: '23', title: 'Lagos tech startup raises record funding', lat: 6.45, lng: 3.40, category: 'business_economy', importance: 1, magnitude: 1, source: 'Bloomberg', publishedAt: new Date().toISOString(), url: 'https://www.bloomberg.com', description: 'Fintech company secures $200M in Series C round.' },
  { id: '24', title: 'Bangkok hosts international food festival', lat: 13.76, lng: 100.50, category: 'food_travel', importance: 1, magnitude: 1, source: 'Reuters', publishedAt: new Date().toISOString(), url: 'https://www.reuters.com', description: '50 nations participate in week-long culinary and cultural exchange.' },
  { id: '25', title: 'New Zealand marine reserve expanded', lat: -41.29, lng: 174.78, category: 'environment_climate', importance: 1, magnitude: 1, source: 'ABC News (AU)', publishedAt: new Date().toISOString(), url: 'https://www.abc.net.au/news', description: 'Protected marine area doubles in size to preserve biodiversity.' },
  { id: '26', title: 'Buenos Aires metro expansion opens', lat: -34.60, lng: -58.38, category: 'traffic_transportation', importance: 1, magnitude: 1, source: 'Associated Press', publishedAt: new Date().toISOString(), url: 'https://apnews.com', description: 'Three new lines add 40km to the growing transit network.' },
  { id: '27', title: 'Singapore AI research center inaugurated', lat: 1.35, lng: 103.82, category: 'science_technology', importance: 1, magnitude: 1, source: 'TechCrunch', publishedAt: new Date().toISOString(), url: 'https://techcrunch.com', description: 'State-of-the-art facility to focus on responsible AI development.' },
  { id: '28', title: 'Cairo museum unveils ancient artifacts', lat: 30.04, lng: 31.24, category: 'arts_music', importance: 1, magnitude: 1, source: 'BBC News', publishedAt: new Date().toISOString(), url: 'https://www.bbc.com', description: 'Newly discovered tomb artifacts from the 18th dynasty go on display.' },
  { id: '29', title: 'Mumbai real estate market sees record deals', lat: 19.08, lng: 72.88, category: 'real_estate', importance: 1, magnitude: 1, source: 'Times of India', publishedAt: new Date().toISOString(), url: 'https://timesofindia.indiatimes.com', description: 'Commercial property transactions reach all-time high in Q1.' },
  { id: '30', title: 'Santiago hosts South American tech conference', lat: -33.45, lng: -70.67, category: 'science_technology', importance: 1, magnitude: 1, source: 'The Verge', publishedAt: new Date().toISOString(), url: 'https://www.theverge.com', description: 'Annual conference attracts 10,000 attendees from across the continent.' },

  // Feed-only items (no coordinates — should appear in ticker/feed but NOT on the globe)
  { id: '31', title: 'Global AI regulation debate heats up ahead of summit', lat: null, lng: null, category: 'science_technology', importance: 3, magnitude: 1, source: 'Associated Press', publishedAt: new Date().toISOString(), url: 'https://apnews.com', description: 'World leaders prepare for landmark discussions on governing artificial intelligence.' },
  { id: '32', title: 'New study links microplastics to cardiovascular risk', lat: null, lng: null, category: 'health_medicine', importance: 2, magnitude: 1, source: 'Reuters', publishedAt: new Date().toISOString(), url: 'https://www.reuters.com', description: 'Researchers find elevated heart disease markers in patients with high microplastic exposure.' },
]
