/**
 * STIX 2.1 export — maps ATLAS investigations to STIX bundles (Phase 4).
 * Minimal SDO set: report, indicator, location, identity, relationship.
 */

const STIX_VERSION = '2.1'
const ATLAS_ID_NS = 'atlas'

/**
 * @param {string} suffix
 * @returns {string}
 */
function stixId(type, suffix) {
  return `${type}--${ATLAS_ID_NS}-${suffix}`
}

/**
 * @param {import('./reportBlueprint.js').ReportBlueprint} blueprint
 * @returns {object}
 */
export function blueprintToStixBundle(blueprint) {
  const now = blueprint.generatedAt || new Date().toISOString()
  const reportId = stixId('report', blueprint.investigationId || Date.now())

  const objects = []

  objects.push({
    type: 'report',
    spec_version: STIX_VERSION,
    id: reportId,
    created: now,
    modified: now,
    name: blueprint.title || 'ATLAS Investigation Report',
    description: blueprint.sections?.find((s) => s.kind === 'summary')?.body
      || blueprint.provenance?.footer
      || 'Generated by ATLAS analyst platform',
    report_types: ['threat-report'],
    published: now,
    object_refs: [],
    labels: [blueprint.classification || 'unclassified'].map((c) => c.toUpperCase()),
    external_references: [{
      source_name: 'ATLAS',
      description: `Template: ${blueprint.templateId}`,
    }],
  })

  const reportRefs = []

  for (const section of blueprint.sections || []) {
    if (section.kind !== 'evidence' || !section.rows?.length) continue

    for (const row of section.rows) {
      const indicatorId = stixId('indicator', hashSuffix(row.title || row.source || String(Math.random())))
      objects.push({
        type: 'indicator',
        spec_version: STIX_VERSION,
        id: indicatorId,
        created: row.timestamp || now,
        modified: now,
        name: row.title || 'Signal',
        description: row.detail || row.summary || '',
        pattern: "[x-atlas:source = '" + (row.source || 'unknown').replace(/'/g, "\\'") + "']",
        pattern_type: 'stix',
        valid_from: row.timestamp || now,
        labels: [row.priority || 'p2', row.dimension || 'narrative'].filter(Boolean),
        external_references: row.sourceUrl ? [{
          source_name: row.source || 'source',
          url: row.sourceUrl,
        }] : undefined,
      })
      reportRefs.push(indicatorId)

      if (row.lat != null && row.lng != null) {
        const locId = stixId('location', hashSuffix(`${row.lat},${row.lng}`))
        objects.push({
          type: 'location',
          spec_version: STIX_VERSION,
          id: locId,
          created: now,
          modified: now,
          latitude: row.lat,
          longitude: row.lng,
          precision: row.latApproximate ? 0.5 : 0.01,
        })
        objects.push({
          type: 'relationship',
          spec_version: STIX_VERSION,
          id: stixId('relationship', hashSuffix(`${indicatorId}-${locId}`)),
          created: now,
          modified: now,
          relationship_type: 'located-at',
          source_ref: indicatorId,
          target_ref: locId,
        })
      }
    }
  }

  for (const entity of blueprint.entities || []) {
    const identityId = stixId('identity', hashSuffix(entity.label || entity.id))
    objects.push({
      type: 'identity',
      spec_version: STIX_VERSION,
      id: identityId,
      created: now,
      modified: now,
      name: entity.label,
      identity_class: entity.kind === 'organization' ? 'organization' : 'individual',
      sectors: entity.kind ? [entity.kind] : undefined,
    })
    reportRefs.push(identityId)
  }

  objects[0].object_refs = reportRefs

  return {
    type: 'bundle',
    id: stixId('bundle', blueprint.investigationId || Date.now()),
    spec_version: STIX_VERSION,
    objects,
  }
}

/**
 * @param {import('./investigationSchema.js').Investigation} investigation
 * @param {import('./reportBlueprint.js').ReportBlueprint} blueprint
 */
export function investigationToStixBundle(investigation, blueprint) {
  const bundle = blueprintToStixBundle(blueprint)

  for (const conn of investigation.connections || []) {
    if (blueprint.redaction?.hideHypotheses && conn.type === 'hypothesis') continue
    bundle.objects.push({
      type: 'relationship',
      spec_version: STIX_VERSION,
      id: stixId('relationship', hashSuffix(`${conn.from}-${conn.to}-${conn.type}`)),
      created: investigation.audit?.updatedAt || new Date().toISOString(),
      modified: investigation.audit?.updatedAt || new Date().toISOString(),
      relationship_type: conn.type === 'fact' ? 'related-to' : 'derived-from',
      description: conn.label || conn.type,
      source_ref: stixId('indicator', hashSuffix(conn.from)),
      target_ref: stixId('indicator', hashSuffix(conn.to)),
      confidence: conn.type === 'fact' ? 90 : 50,
    })
  }

  return bundle
}

/**
 * @param {string} input
 * @returns {string}
 */
function hashSuffix(input) {
  let hash = 0x811c9dc5
  for (let i = 0; i < input.length; i++) {
    hash ^= input.charCodeAt(i)
    hash = (hash * 0x01000193) >>> 0
  }
  return hash.toString(16).padStart(8, '0')
}
